name: flutter_api_client_example
description: Example app for flutter_api_client package.
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_api_client:
    path: ../

dev_dependencies:
  build_runner: ^2.15.0
  source_gen: ^4.2.3
  flutter_test:
    sdk: flutter
