include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - avoid_redundant_argument_values
    - cancel_subscriptions
    - close_sinks
