builders:
  api_spec_builder:
    import: "package:flutter_api_client/src/gen/api_spec_builder.dart"
    builder_factories: ["apiSpecBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
