// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'my_spec.dart';

// **************************************************************************
// _ApiSpecGenerator
// **************************************************************************

// Generated by flutter_api_client — do not edit.
// Run `dart run build_runner build` to regenerate.

ApiSpec get $generatedSpec => mySpec;
